/**
 * Pure emitters for the generated token artifacts. Kept side-effect-free so the
 * byte-identity test can import them and diff against the committed files;
 * `generate-tokens.ts` imports these and writes. Deterministic (fixed key
 * order, one trailing newline).
 */
import {
  hexToRgb,
  ramps,
  semanticDark,
  semanticLight,
  terminal,
  verdictStyles,
  VERDICTS,
  type TerminalSlot,
} from '../src/tokens.js';

export function emitColorsCss(): string {
  const lines: string[] = [];
  lines.push('/* GENERATED by scripts/generate-tokens.ts from src/tokens.ts — do not edit.');
  lines.push('   Edit the token source and re-run `generate-tokens`.');
  lines.push('');
  lines.push('   USAGE LAW: GREEN IS EARNED (passed work only); RED IS REAL FAILURE only. */');
  lines.push('');
  lines.push(':root {');
  lines.push('  /* base ramps — the only raw hexes */');
  for (const [family, steps] of Object.entries(ramps)) {
    for (const [step, hex] of Object.entries(steps)) {
      lines.push(`  --pg-${family}-${step}: ${hex};`);
    }
  }
  lines.push('');
  lines.push('  /* semantic aliases — light */');
  for (const [name, value] of Object.entries(semanticLight)) {
    lines.push(`  --pg-${name}: ${value};`);
  }
  lines.push('');
  lines.push('  /* terminal surface — always dark, theme-independent */');
  for (const slot of Object.values(terminal) as TerminalSlot[]) {
    lines.push(`  --pg-term-${slot.name}: ${slot.hex};`);
  }
  lines.push('}');
  lines.push('');
  lines.push('[data-theme="dark"] {');
  for (const [name, value] of Object.entries(semanticDark)) {
    lines.push(`  --pg-${name}: ${value};`);
  }
  lines.push('}');
  return lines.join('\n') + '\n';
}

export function emitTheme(): string {
  const slots = Object.values(terminal) as TerminalSlot[];
  const slotNames = slots.map((s) => s.name);
  const l: string[] = [];
  l.push('/* GENERATED by scripts/generate-tokens.ts from src/tokens.ts — do not edit. */');
  l.push('// Terminal theme: truecolor triplets + a 16-colour ANSI floor per slot.');
  l.push('// The glyph carries status, so under NO_COLOR / a non-TTY stdout nothing is');
  l.push('// lost — the colorizer simply returns the text unpainted.');
  l.push('');
  l.push(`export type TermSlot = ${slotNames.map((n) => `'${n}'`).join(' | ')};`);
  l.push('');
  l.push('const TRUECOLOR: Record<TermSlot, [number, number, number]> = {');
  for (const s of slots) {
    const [r, g, b] = hexToRgb(s.hex);
    l.push(`  ${s.name}: [${r}, ${g}, ${b}],`);
  }
  l.push('};');
  l.push('');
  l.push('const ANSI16: Record<TermSlot, { code: number; bright?: number }> = {');
  for (const s of slots) {
    const bright = s.ansiBright !== undefined ? `, bright: ${s.ansiBright}` : '';
    l.push(`  ${s.name}: { code: ${s.ansi16}${bright} },`);
  }
  l.push('};');
  l.push('');
  l.push("export type ColorTier = 'truecolor' | 'ansi16' | 'none';");
  l.push('');
  l.push('/** Decide the colour tier ONCE: no escapes under NO_COLOR or a non-TTY');
  l.push(' * stdout; truecolor when the terminal advertises it; else the 16-colour');
  l.push(' * floor. Nothing downstream re-checks isTTY. */');
  l.push('export function colorTier(');
  l.push('  env: NodeJS.ProcessEnv = process.env,');
  l.push('  isTTY: boolean = Boolean(process.stdout && process.stdout.isTTY),');
  l.push('): ColorTier {');
  l.push("  if (!isTTY || (env['NO_COLOR'] !== undefined && env['NO_COLOR'] !== '')) return 'none';");
  l.push("  const ct = env['COLORTERM'];");
  l.push("  if (ct === 'truecolor' || ct === '24bit') return 'truecolor';");
  l.push("  return 'ansi16';");
  l.push('}');
  l.push('');
  l.push('/** Paint `text` in a slot for the given tier. `none` returns text as-is. */');
  l.push('export function paint(slot: TermSlot, text: string, tier: ColorTier = colorTier()): string {');
  l.push("  if (tier === 'none') return text;");
  l.push("  if (tier === 'truecolor') {");
  l.push('    const [r, g, b] = TRUECOLOR[slot];');
  l.push('    return `\\x1b[38;2;${r};${g};${b}m${text}\\x1b[0m`;');
  l.push('  }');
  l.push('  return `\\x1b[${ANSI16[slot].code}m${text}\\x1b[0m`;');
  l.push('}');
  l.push('');
  l.push('/** The closed ledger vocabulary → glyph (source of truth) + colour slot. */');
  l.push('export const VERDICTS = [' + VERDICTS.map((v) => `'${v}'`).join(', ') + '] as const;');
  l.push('export type Verdict = (typeof VERDICTS)[number];');
  l.push('');
  l.push('export const glyph: Record<Verdict, string> = {');
  for (const v of VERDICTS) l.push(`  ${v}: '${verdictStyles[v].glyph}',`);
  l.push('};');
  l.push('');
  l.push('export const verdictSlot: Record<Verdict, TermSlot> = {');
  for (const v of VERDICTS) l.push(`  ${v}: '${verdictStyles[v].slot}',`);
  l.push('};');
  return l.join('\n') + '\n';
}
