/* GENERATED by scripts/generate-tokens.ts from src/tokens.ts — do not edit. */
// Terminal theme: truecolor triplets + a 16-colour ANSI floor per slot.
// The glyph carries status, so under NO_COLOR / a non-TTY stdout nothing is
// lost — the colorizer simply returns the text unpainted.

export type TermSlot = 'bg' | 'fg' | 'dim' | 'green' | 'red' | 'amber' | 'human' | 'plan' | 'stale' | 'border';

const TRUECOLOR: Record<TermSlot, [number, number, number]> = {
  bg: [20, 19, 13],
  fg: [231, 228, 219],
  dim: [143, 138, 123],
  green: [79, 208, 138],
  red: [244, 119, 107],
  amber: [232, 180, 74],
  human: [111, 168, 245],
  plan: [99, 182, 194],
  stale: [179, 154, 82],
  border: [46, 43, 37],
};

const ANSI16: Record<TermSlot, { code: number; bright?: number }> = {
  bg: { code: 40 },
  fg: { code: 37 },
  dim: { code: 90 },
  green: { code: 32, bright: 92 },
  red: { code: 31, bright: 91 },
  amber: { code: 33, bright: 93 },
  human: { code: 34, bright: 94 },
  plan: { code: 36, bright: 96 },
  stale: { code: 33 },
  border: { code: 90 },
};

export type ColorTier = 'truecolor' | 'ansi16' | 'none';

/** Decide the colour tier ONCE: no escapes under NO_COLOR or a non-TTY
 * stdout; truecolor when the terminal advertises it; else the 16-colour
 * floor. Nothing downstream re-checks isTTY. */
export function colorTier(
  env: NodeJS.ProcessEnv = process.env,
  isTTY: boolean = Boolean(process.stdout && process.stdout.isTTY),
): ColorTier {
  if (!isTTY || (env['NO_COLOR'] !== undefined && env['NO_COLOR'] !== '')) return 'none';
  const ct = env['COLORTERM'];
  if (ct === 'truecolor' || ct === '24bit') return 'truecolor';
  return 'ansi16';
}

/** Paint `text` in a slot for the given tier. `none` returns text as-is. */
export function paint(slot: TermSlot, text: string, tier: ColorTier = colorTier()): string {
  if (tier === 'none') return text;
  if (tier === 'truecolor') {
    const [r, g, b] = TRUECOLOR[slot];
    return `\x1b[38;2;${r};${g};${b}m${text}\x1b[0m`;
  }
  return `\x1b[${ANSI16[slot].code}m${text}\x1b[0m`;
}

/** The closed ledger vocabulary → glyph (source of truth) + colour slot. */
export const VERDICTS = ['passed', 'failed', 'partial', 'skipped', 'operator', 'blocked'] as const;
export type Verdict = (typeof VERDICTS)[number];

// `as const satisfies` keeps each value a readonly literal (a consumer
// cannot repaint a verdict) while still checking the shape.
export const glyph = {
  passed: '✓',
  failed: '✗',
  partial: '⚠',
  skipped: '=',
  operator: '→',
  blocked: '!',
} as const satisfies Record<Verdict, string>;

export const verdictSlot = {
  passed: 'green',
  failed: 'red',
  partial: 'amber',
  skipped: 'dim',
  operator: 'human',
  blocked: 'stale',
} as const satisfies Record<Verdict, TermSlot>;
